# Generated by Django 4.0.3 on 2022-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_senya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denuncia', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='senya',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
