# Generated by Django 4.0.3 on 2022-03-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_denuncia_senya_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='denuncia',
        ),
    ]
