# Generated by Django 4.0.3 on 2022-03-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_alter_uploader_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='denuncia',
        ),
    ]
