# Generated by Django 4.0.3 on 2022-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0013_remove_denuncia_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denuncia',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Senya',
        ),
    ]
