# Generated by Django 4.0.3 on 2022-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0016_alter_denuncia_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='denuncia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
